name: HandOff
api-version: 1.14
version: 1.1.0
description: This plugin adds shops to your Minecraft server.
author: ConsumerJunk
website: consumerjunk.net
main: net.consumerjunk.handoff.Main
permissions:
  handoff.adminshop:
    description: This permission allows Admins to create stores with infinite.
    default: false
